[manifest]
version = "1.0"
created_at = "2026-01-08T16:05:14.302406670Z"
pipeline_run = "harvest-2026-01-08-1605"

[binaries.songbird]
name = "songbird"
version = "3.19.0"
git_commit = "unknown"
build_date = "2026-01-08T16:05:14.297539128Z"
sha256 = "21b4eb1cc86b0997acd454ae165de21379db158bf56b343a7ffbb966ebeab584"
size_bytes = 28314760
source_repo = "ecoPrimals/phase1/songbird"
features = [
    "btsp-client",
    "port-free",
]

[binaries.tower]
name = "tower"
version = "0.1.0"
git_commit = "unknown"
build_date = "2026-01-08T16:05:14.277241690Z"
sha256 = "2aa8bb3ededb8184f5808d25b71657fb9af16136bf0c5db1cda0f9bf040fbfca"
size_bytes = 7319408
source_repo = "biomeOS"
features = []

[binaries.beardog]
name = "beardog-server"
version = "0.15.0"
git_commit = "unknown"
build_date = "2026-01-08T16:05:14.302399731Z"
sha256 = "0318b383372b776f2a871cc5445eafe6fa1ceace1efdc53f849d6bcf1b0a9570"
size_bytes = 5780064
source_repo = "ecoPrimals/phase1/beardog"
features = [
    "btsp-api",
    "unix-socket",
]

[compatibility]
min_tower_version = "0.6.0"
min_beardog_version = "0.15.0"
min_songbird_version = "3.19.0"
