// SPDX-License-Identifier: AGPL-3.0-only
//
// Copyright 2025 ecoPrimals Project
// Licensed under the Affero General Public License v3.0.
// See LICENSE file in the project root or visit https://www.gnu.org/licenses/agpl-3.0.html

//! Documentation generation for spores
//!
//! Handles README and manifest creation.

use std::fs;
use std::path::PathBuf;
use tokio::fs as async_fs;
use tracing::{debug, info};

use super::core::Spore;
use crate::error::SporeResult;
use crate::spore_types::SporeType;

/// Trait for documentation operations on spores
pub(super) trait DocumentationOps {
    /// Create README with instructions
    fn create_readme(&self) -> impl std::future::Future<Output = SporeResult<()>> + Send;

    /// Create spore manifest (metadata about this spore)
    fn create_spore_manifest(&self) -> impl std::future::Future<Output = SporeResult<()>> + Send;
}

impl DocumentationOps for Spore {
    /// Create README with instructions
    async fn create_readme(&self) -> SporeResult<()> {
        let usage_section = match self.config.spore_type {
            SporeType::Cold => {
                r"## Usage (ColdSpore - Archive)

This is a **ColdSpore** - genetic material preserved for storage.

To activate this spore:
1. Copy to ext4/ext3 filesystem (preserves permissions)
2. OR convert to LiveSpore: `biomeos spore convert --type live`
3. Then deploy as normal

ColdSpores are ideal for:
- Long-term storage
- Distribution archives
- Backup copies
- Non-FAT32 transfers
"
            }
            SporeType::Live => {
                r"## Usage (LiveSpore - Deployable)

This is a **LiveSpore** - ready for immediate deployment!

Boot your machine from this USB drive, or mount and run:

```bash
cd /path/to/mount/biomeOS
./deploy.sh
```

LiveSpores automatically handle:
- FAT32 filesystem limitations
- Permission setup
- Execution environment
"
            }
        };

        let readme = format!(
            r"# biomeOS {}: {}

Node ID: {}
Type: {} {}
Created: {}

{}

## Architecture

This spore uses a composable security architecture:

- **biomeOS**: Orchestration layer (this spore)
- **BearDog**: Security layer (reads `.family.seed`, handles all crypto)
- **Songbird**: Discovery layer (UDP multicast peer discovery)

## Genetic Lineage

The `.family.seed` file contains cryptographic material that establishes
this tower's family membership. BearDog processes this seed using HKDF-SHA256
to derive unique child keys while maintaining family relationships.

**DO NOT share or copy .family.seed publicly!**

## Files

- `.family.seed` - Family cryptographic seed (600 permissions)
- `tower.toml` - Tower configuration
- `primals/` - Primal binaries (beardog-server, songbird)
- `bin/tower` - Tower orchestrator
{}

---

Generated by biomeOS spore system
",
            self.config.spore_type,
            self.config.label,
            self.config.node_id,
            self.config.spore_type.emoji(),
            self.config.spore_type,
            chrono::Utc::now().to_rfc3339(),
            usage_section,
            if self.config.spore_type.requires_execution_env() {
                "\n- `deploy.sh` - Deployment script (LiveSpore)"
            } else {
                ""
            },
        );

        let readme_path = self.root_path.join("README.md");
        async_fs::write(&readme_path, readme).await?;
        debug!("Created README.md");

        Ok(())
    }

    /// Create spore manifest (metadata about this spore)
    async fn create_spore_manifest(&self) -> SporeResult<()> {
        use crate::manifest::{BinaryManifest, SporeManifest};
        use sha2::{Digest, Sha256};

        info!("Creating .manifest.toml with SHA256 checksums");

        // Load parent seed to compute hash
        let parent_seed_path = self.root_path.join(".family.seed");
        let parent_seed_bytes = fs::read(&parent_seed_path)?;
        let mut hasher = Sha256::new();
        hasher.update(&parent_seed_bytes);
        let parent_seed_hash = format!("{:x}", hasher.finalize());

        // Child seed hash is same for genesis spores (parent == child)
        let child_seed_hash = parent_seed_hash.clone();

        // EVOLVED (Jan 27, 2026): Get NAT/family from config or environment
        let family_id = Self::resolve_family_id();

        // Create spore manifest
        let mut manifest = SporeManifest::new(
            self.config.node_id.clone(),
            family_id,
            self.config.spore_type.to_string(),
            chrono::Utc::now().format("%Y-%m-%d").to_string(),
            parent_seed_hash,
            child_seed_hash,
        );

        // Load plasmidBin manifest to get binary info
        let nucleus_path = PathBuf::from("plasmidBin");
        if nucleus_path.exists() {
            match BinaryManifest::from_nucleus(&nucleus_path) {
                Ok(nucleus_manifest) => {
                    // Add binary info from nucleus manifest
                    for (_key, binary) in nucleus_manifest.binaries {
                        manifest.add_binary(
                            binary.name.clone(),
                            binary.version.clone(),
                            binary.sha256.clone(),
                        );
                    }
                    info!(
                        "Added {} binaries to spore manifest",
                        manifest.binaries.len()
                    );
                }
                Err(e) => {
                    debug!("Could not load plasmidBin manifest: {}", e);
                    // Continue without binary info
                }
            }
        }

        // Save manifest
        manifest.save(&self.root_path)?;
        info!("Created .manifest.toml");

        Ok(())
    }
}

impl Spore {
    /// Resolve family ID from environment, config files, or default
    ///
    /// EVOLVED (Jan 27, 2026): XDG-compliant family resolution
    ///
    /// Uses centralized family discovery from biomeos_core.
    fn resolve_family_id() -> String {
        // Delegate to centralized family discovery
        // This ensures consistent discovery across the entire codebase
        biomeos_core::family_discovery::get_family_id()
    }
}
