#!/bin/bash
# Create Test USB Family Seed for Development
# This creates a test seed for development and demonstration purposes

set -euo pipefail

TEST_SEED_DIR="${1:-/tmp/biomeos-test}"
SEED_FILE="$TEST_SEED_DIR/.family.seed"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 Test USB Family Seed Generator"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create directory
mkdir -p "$TEST_SEED_DIR"
echo "📁 Directory: $TEST_SEED_DIR"

# Generate 32-byte (256-bit) seed
echo "🎲 Generating 256-bit random seed..."
dd if=/dev/urandom of="$SEED_FILE" bs=32 count=1 2>/dev/null

# Set secure permissions
chmod 600 "$SEED_FILE"

# Calculate hash for verification
SEED_HASH=$(sha256sum "$SEED_FILE" | awk '{print $1}')
SEED_PREVIEW=$(echo "$SEED_HASH" | head -c 16)

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Test Seed Created Successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Location:     $SEED_FILE"
echo "📏 Size:         32 bytes (256 bits)"
echo "🔒 Permissions:  0600 (owner read/write only)"
echo "🔑 Hash Preview: $SEED_PREVIEW..."
echo ""

# Create usage instructions
cat > "$TEST_SEED_DIR/README.txt" << EOF
═══════════════════════════════════════════════════════════════
🧬 TEST USB FAMILY SEED
═══════════════════════════════════════════════════════════════

Created: $(date)
Location: $SEED_FILE
Hash: $SEED_HASH

⚠️  WARNING: TEST SEED ONLY - NOT FOR PRODUCTION USE!

This seed was generated for development and demonstration purposes.
For production deployments, use a hardware-secured seed generation
process with proper entropy sources and backup procedures.

═══════════════════════════════════════════════════════════════
USAGE
═══════════════════════════════════════════════════════════════

Export the seed path:

    export BIOMEOS_USB_SEED="$SEED_FILE"

Deploy all 3 atomics:

    cd /home/eastgate/Development/ecoPrimals/phase2/biomeOS
    ./scripts/deploy-all-atomics-lineage.sh

Or deploy individually:

    ./scripts/deploy-tower-lineage.sh
    ./scripts/deploy-node-lineage.sh
    ./scripts/deploy-nest-lineage.sh

Verify lineage recognition:

    ./scripts/verify-lineage-cooperation.sh

═══════════════════════════════════════════════════════════════
GENETIC LINEAGE MODEL
═══════════════════════════════════════════════════════════════

This seed serves as the "parent DNA" for genetic lineage:

    USB Seed (parent)
        ↓ SHA256(seed || node_id || batch)
        ├─→ Tower (child seed)
        ├─→ Node  (child seed)
        └─→ Nest  (child seed)

Each atomic gets a unique child seed derived from:
- Parent seed (this file)
- Node ID (tower, node, nest)
- Deployment batch (date)

All children can cryptographically verify they share the same
parent lineage, enabling automatic trust and cooperation.

═══════════════════════════════════════════════════════════════
Generated by: create-test-seed.sh
Different orders of the same architecture. 🍄🐸
═══════════════════════════════════════════════════════════════
EOF

chmod 444 "$TEST_SEED_DIR/README.txt"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Documentation Created"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Read usage instructions:"
echo "   cat $TEST_SEED_DIR/README.txt"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Quick Start"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Export the seed path:"
echo "   export BIOMEOS_USB_SEED=\"$SEED_FILE\""
echo ""
echo "2. Deploy all atomics:"
echo "   ./scripts/deploy-all-atomics-lineage.sh"
echo ""
echo "3. Verify lineage:"
echo "   ./scripts/verify-lineage-cooperation.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Different orders of the same architecture. 🍄🐸"
echo ""

