// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2025-2026 ecoPrimals Project

//! Route table: method name → route tag mapping for the Neural API.
//!
//! Pure data — separates routing definitions from dispatch behavior in `routing.rs`.

/// Route tag for dispatch. Each variant maps to a handler in `routing.rs`.
#[derive(Clone, Copy, Debug)]
pub(super) enum Route {
    GraphList,
    GraphGet,
    GraphSave,
    GraphExecute,
    GraphStatus,
    GraphExecutePipeline,
    GraphStartContinuous,
    GraphPauseContinuous,
    GraphResumeContinuous,
    GraphStopContinuous,
    GraphSuggestOptimizations,
    TopologyGet,
    TopologyPrimals,
    TopologyProprioception,
    TopologyMetrics,
    TopologyRescan,
    NicheList,
    NicheDeploy,
    LifecycleStatus,
    LifecycleGet,
    LifecycleRegister,
    LifecycleResurrect,
    LifecycleApoptosis,
    LifecycleShutdownAll,
    LifecycleComposition,
    CompositionHealth,
    ProtocolStatus,
    ProtocolEscalate,
    ProtocolFallback,
    ProtocolMetrics,
    ProtocolRegisterPrimal,
    ProtocolRegisterConnection,
    ProtocolRecordRequest,
    ProtocolStartMonitoring,
    ProtocolStopMonitoring,
    GraphProtocolMap,
    GateRegister,
    GateList,
    BatchRouteRegister,
    CapabilityRegister,
    CapabilityDiscover,
    CapabilityList,
    CapabilityProviders,
    CapabilityResolve,
    CapabilityResolveSingle,
    CapabilityMetrics,
    CapabilityCall,
    CapabilityDiscoverTranslations,
    CapabilityListTranslations,
    RoutingWeights,
    RoutingExplain,
    CompositionPatterns,
    CompositionPatternsReload,
    CompositionPlanTier,
    CapabilityUtilization,
    McpToolsList,
    Agent,
    ProxyHttp,
    InferenceSchedule,
    InferenceGates,
    InferenceRegisterProvider,
    InferenceProviders,
    InferenceComplete,
    InferenceEmbed,
    InferenceModels,
    SemanticCapabilityCall,
    HealthCheck,
    HealthLiveness,
    HealthReadiness,
    BtspEscalate,
    BtspStatus,
    BtspNegotiate,
    GraphTickStatus,
    GraphVerify,
    AuthCheck,
    AuthMode,
    AuthPeerInfo,
    CompositionReload,
    CompositionStatus,
    CompositionDeploy,
    CompositionDeployShadow,
    SpringStatus,
    MethodRegister,
    SignalDispatch,
    SignalList,
    SignalSchema,
    PrimalAnnounce,
    WeightHealth,
    IdentityGet,
    SporeInstantiate,
    NucleusIngestSpore,
    NucleusEmitSpore,
    ManifestGateProfile,
}

/// Table-driven handler registry: method name → route.
/// Multiple method names may map to the same route (e.g. `neural_api.list_graphs` | `graph.list`).
const ROUTE_TABLE: &[(&str, Route)] = &[
    ("neural_api.list_graphs", Route::GraphList),
    ("graph.list", Route::GraphList),
    ("neural_api.get_graph", Route::GraphGet),
    ("graph.get", Route::GraphGet),
    ("graph.load", Route::GraphGet),
    ("neural_api.save_graph", Route::GraphSave),
    ("graph.save", Route::GraphSave),
    ("neural_api.execute_graph", Route::GraphExecute),
    ("graph.execute", Route::GraphExecute),
    ("neural_api.get_execution_status", Route::GraphStatus),
    ("graph.status", Route::GraphStatus),
    ("graph.execute_pipeline", Route::GraphExecutePipeline),
    ("neural_api.execute_pipeline", Route::GraphExecutePipeline),
    ("graph.start_continuous", Route::GraphStartContinuous),
    ("neural_api.start_continuous", Route::GraphStartContinuous),
    ("graph.pause_continuous", Route::GraphPauseContinuous),
    ("neural_api.pause_continuous", Route::GraphPauseContinuous),
    ("graph.resume_continuous", Route::GraphResumeContinuous),
    ("neural_api.resume_continuous", Route::GraphResumeContinuous),
    ("graph.stop_continuous", Route::GraphStopContinuous),
    ("neural_api.stop_continuous", Route::GraphStopContinuous),
    ("graph.tick_status", Route::GraphTickStatus),
    ("graph.verify", Route::GraphVerify),
    ("graph.suggest_optimizations", Route::GraphSuggestOptimizations),
    ("neural_api.suggest_optimizations", Route::GraphSuggestOptimizations),
    ("neural_api.get_topology", Route::TopologyGet),
    ("topology.get", Route::TopologyGet),
    ("neural_api.get_primals", Route::TopologyPrimals),
    ("topology.primals", Route::TopologyPrimals),
    ("primal.list", Route::TopologyPrimals),
    ("list", Route::TopologyPrimals),
    ("neural_api.get_proprioception", Route::TopologyProprioception),
    ("topology.proprioception", Route::TopologyProprioception),
    ("neural_api.get_metrics", Route::TopologyMetrics),
    ("topology.metrics", Route::TopologyMetrics),
    ("topology.rescan", Route::TopologyRescan),
    ("neural_api.list_niche_templates", Route::NicheList),
    ("niche.list", Route::NicheList),
    ("neural_api.deploy_niche", Route::NicheDeploy),
    ("niche.deploy", Route::NicheDeploy),
    ("lifecycle.status", Route::LifecycleStatus),
    ("lifecycle.get", Route::LifecycleGet),
    ("lifecycle.register", Route::LifecycleRegister),
    ("lifecycle.resurrect", Route::LifecycleResurrect),
    ("lifecycle.apoptosis", Route::LifecycleApoptosis),
    ("lifecycle.shutdown_all", Route::LifecycleShutdownAll),
    ("lifecycle.composition", Route::LifecycleComposition),
    ("composition.health", Route::CompositionHealth),
    ("composition.tower_health", Route::CompositionHealth),
    ("composition.node_health", Route::CompositionHealth),
    ("composition.nest_health", Route::CompositionHealth),
    ("composition.nucleus_health", Route::CompositionHealth),
    ("protocol.status", Route::ProtocolStatus),
    ("protocol.escalate", Route::ProtocolEscalate),
    ("protocol.fallback", Route::ProtocolFallback),
    ("protocol.metrics", Route::ProtocolMetrics),
    ("protocol.register_primal", Route::ProtocolRegisterPrimal),
    ("protocol.register_connection", Route::ProtocolRegisterConnection),
    ("protocol.record_request", Route::ProtocolRecordRequest),
    ("protocol.start_monitoring", Route::ProtocolStartMonitoring),
    ("protocol.stop_monitoring", Route::ProtocolStopMonitoring),
    ("graph.protocol_map", Route::GraphProtocolMap),
    ("gate.register", Route::GateRegister),
    ("gate.list", Route::GateList),
    ("route.register", Route::BatchRouteRegister),
    ("capability.register", Route::CapabilityRegister),
    ("capability.discover", Route::CapabilityDiscover),
    ("neural_api.discover_capability", Route::CapabilityDiscover),
    ("discovery.find_by_capability", Route::CapabilityDiscover),
    ("capability.list", Route::CapabilityList),
    ("capabilities.list", Route::CapabilityList),
    ("capability.providers", Route::CapabilityProviders),
    ("capability.route", Route::CapabilityResolve),
    ("neural_api.route_to_primal", Route::CapabilityResolve),
    ("capability.resolve", Route::CapabilityResolveSingle),
    ("ipc.resolve", Route::CapabilityResolveSingle),
    ("capability.metrics", Route::CapabilityMetrics),
    ("neural_api.get_routing_metrics", Route::CapabilityMetrics),
    ("neural_api.routing_weights", Route::RoutingWeights),
    ("neural_api.route_explain", Route::RoutingExplain),
    ("neural_api.composition_patterns", Route::CompositionPatterns),
    ("neural_api.composition_patterns_reload", Route::CompositionPatternsReload),
    ("composition.patterns.reload", Route::CompositionPatternsReload),
    ("neural_api.plan_tier", Route::CompositionPlanTier),
    ("neural_api.utilization", Route::CapabilityUtilization),
    ("neural_api.weight_health", Route::WeightHealth),
    ("weight_health", Route::WeightHealth),
    ("capability.call", Route::CapabilityCall),
    ("capability.discover_translations", Route::CapabilityDiscoverTranslations),
    ("capability.discover_translation", Route::CapabilityDiscoverTranslations),
    ("capability.list_translations", Route::CapabilityListTranslations),
    ("inference.schedule", Route::InferenceSchedule),
    ("inference.gates", Route::InferenceGates),
    ("inference.register_provider", Route::InferenceRegisterProvider),
    ("inference.providers", Route::InferenceProviders),
    ("inference.complete", Route::InferenceComplete),
    ("inference.embed", Route::InferenceEmbed),
    ("inference.models", Route::InferenceModels),
    ("mcp.tools.list", Route::McpToolsList),
    ("mcp.tools_list", Route::McpToolsList),
    ("agent.create", Route::Agent),
    ("agent.list", Route::Agent),
    ("agent.get", Route::Agent),
    ("agent.remove", Route::Agent),
    ("agent.meld", Route::Agent),
    ("agent.split", Route::Agent),
    ("agent.resolve", Route::Agent),
    ("agent.route", Route::Agent),
    ("agent.auto_meld", Route::Agent),
    ("neural_api.proxy_http", Route::ProxyHttp),
    ("health.check", Route::HealthCheck),
    ("health.liveness", Route::HealthLiveness),
    ("health.readiness", Route::HealthReadiness),
    ("auth.check", Route::AuthCheck),
    ("auth.mode", Route::AuthMode),
    ("auth.peer_info", Route::AuthPeerInfo),
    ("composition.reload", Route::CompositionReload),
    ("composition.status", Route::CompositionStatus),
    ("composition.deploy", Route::CompositionDeploy),
    ("composition.deploy.shadow", Route::CompositionDeployShadow),
    ("identity.get", Route::IdentityGet),
    ("identity", Route::IdentityGet),
    ("primal.announce", Route::PrimalAnnounce),
    ("neural_api.primal_announce", Route::PrimalAnnounce),
    ("signal.dispatch", Route::SignalDispatch),
    ("neural_api.signal_dispatch", Route::SignalDispatch),
    ("signal.list", Route::SignalList),
    ("neural_api.signal_list", Route::SignalList),
    ("signal.schema", Route::SignalSchema),
    ("neural_api.signal_schema", Route::SignalSchema),
    ("biomeos.spring_status", Route::SpringStatus),
    ("method.register", Route::MethodRegister),
    ("spore.instantiate", Route::SporeInstantiate),
    ("nucleus.ingest_spore", Route::NucleusIngestSpore),
    ("nucleus.ingest", Route::NucleusIngestSpore),
    ("nucleus.emit_spore", Route::NucleusEmitSpore),
    ("nucleus.emit", Route::NucleusEmitSpore),
    ("manifest.gate_profile", Route::ManifestGateProfile),
    ("btsp.escalate", Route::BtspEscalate),
    ("btsp.status", Route::BtspStatus),
    ("btsp.negotiate", Route::BtspNegotiate),
    // Signal-tier semantic routes: direct method-name → signal graph interception
    ("nest.store", Route::SemanticCapabilityCall),
    ("nest.commit", Route::SemanticCapabilityCall),
    ("nest.retrieve", Route::SemanticCapabilityCall),
    ("nest.sync", Route::SemanticCapabilityCall),
    ("tower.publish", Route::SemanticCapabilityCall),
    ("tower.authenticate", Route::SemanticCapabilityCall),
    ("tower.discover", Route::SemanticCapabilityCall),
    ("tower.health", Route::SemanticCapabilityCall),
    ("tower.bootstrap", Route::SemanticCapabilityCall),
    ("node.compute", Route::SemanticCapabilityCall),
    ("braid.partial_update", Route::SemanticCapabilityCall),
    ("braid.complete", Route::SemanticCapabilityCall),
    ("meta.observe", Route::SemanticCapabilityCall),
    ("meta.intent", Route::SemanticCapabilityCall),
    ("meta.render", Route::SemanticCapabilityCall),
    ("meta.health", Route::SemanticCapabilityCall),
    ("meta.deploy", Route::SemanticCapabilityCall),
    ("mesh.status", Route::SemanticCapabilityCall),
    ("mesh.find_path", Route::SemanticCapabilityCall),
    ("mesh.announce", Route::SemanticCapabilityCall),
    ("mesh.peers", Route::SemanticCapabilityCall),
    ("mesh.health_check", Route::SemanticCapabilityCall),
    ("punch.request", Route::SemanticCapabilityCall),
    ("punch.status", Route::SemanticCapabilityCall),
    ("punch.coordinate", Route::SemanticCapabilityCall),
    ("stun.discover", Route::SemanticCapabilityCall),
    ("stun.detect_nat_type", Route::SemanticCapabilityCall),
    ("stun.probe_port_pattern", Route::SemanticCapabilityCall),
    ("relay.serve", Route::SemanticCapabilityCall),
    ("relay.status", Route::SemanticCapabilityCall),
    ("relay.allocate", Route::SemanticCapabilityCall),
    ("relay.authorize", Route::SemanticCapabilityCall),
    ("onion.create_service", Route::SemanticCapabilityCall),
    ("onion.get_address", Route::SemanticCapabilityCall),
    ("onion.connect", Route::SemanticCapabilityCall),
    ("onion.status", Route::SemanticCapabilityCall),
];

pub(super) fn lookup_route(method: &str) -> Option<Route> {
    ROUTE_TABLE
        .iter()
        .find(|(m, _)| *m == method)
        .map(|(_, r)| *r)
}
