#!/usr/bin/env bash
#
# LiveSpore Deployment Script
# Generated by biomeOS Neural API Spore Imprinting
#
# This script properly initializes a LiveSpore with:
# - 64-byte genetic lineage seed (genesis + node_key)
# - Deterministic broadcast key via Blake3
# - Dark Forest encrypted discovery
# - Tower Atomic architecture (BearDog + Songbird)
#
set -euo pipefail

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CONFIGURATION (populated during imprinting)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FAMILY_ID="${FAMILY_ID:-__FAMILY_ID__}"
NODE_ID="${NODE_ID:-__NODE_ID__}"
PARENT_NODE="${PARENT_NODE:-genesis}"
SPORE_VERSION="${SPORE_VERSION:-__SPORE_VERSION__}"

# Resolve script location (works on FAT32 USBs)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPORE_ROOT="${SCRIPT_DIR}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌱 LiveSpore Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Family:  $FAMILY_ID"
echo "Node:    $NODE_ID"
echo "Parent:  $PARENT_NODE"
echo "Version: $SPORE_VERSION"
echo "Root:    $SPORE_ROOT"
echo ""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 1: VERIFY GENETIC LINEAGE (64-byte seed)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
echo "🧬 Verifying genetic lineage..."

SEED_FILE="$SPORE_ROOT/.family.seed"
if [[ ! -f "$SEED_FILE" ]]; then
    echo "❌ Error: .family.seed not found"
    echo "   This spore has no genetic lineage!"
    echo "   Use Neural API to imprint this spore first."
    exit 1
fi

# Verify seed size (64 bytes: 32 genesis + 32 node_key)
SEED_SIZE=$(stat -c%s "$SEED_FILE" 2>/dev/null || stat -f%z "$SEED_FILE" 2>/dev/null)
if [[ "$SEED_SIZE" -ne 64 ]]; then
    echo "❌ Error: Invalid seed size ($SEED_SIZE bytes, expected 64)"
    echo "   Seed structure: [32 bytes genesis] + [32 bytes node_key]"
    exit 1
fi

echo "✅ Genetic lineage verified (64 bytes)"
echo "   [0-31]  genesis   - Shared family root"
echo "   [32-63] node_key  - Unique node identity"

# Export seed as base64 for security provider
export FAMILY_SEED=$(base64 -w0 "$SEED_FILE")
export GENESIS_SEED=$(head -c 32 "$SEED_FILE" | base64 -w0)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 2: HANDLE FAT32 FILESYSTEM (USB limitation)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FAT32 doesn't support Unix permissions, so copy binaries to /tmp
WORK_DIR=$(mktemp -d)
echo ""
echo "📂 Working directory: $WORK_DIR"

# Copy binaries and make executable
cp "$SPORE_ROOT/primals/beardog" "$WORK_DIR/beardog"
cp "$SPORE_ROOT/primals/songbird" "$WORK_DIR/songbird"
chmod +x "$WORK_DIR/beardog" "$WORK_DIR/songbird"

# Copy seed file to work dir (protected permissions)
cp "$SEED_FILE" "$WORK_DIR/.family.seed"
chmod 600 "$WORK_DIR/.family.seed"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 3: CONFIGURE PRIMAL SOCKETS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export BEARDOG_SOCKET="/tmp/beardog-${FAMILY_ID}-${NODE_ID}.sock"
export SONGBIRD_SOCKET="/tmp/songbird-${FAMILY_ID}-${NODE_ID}.sock"
export FAMILY_ID="$FAMILY_ID"
export NODE_ID="$NODE_ID"
export FAMILY_ID="$FAMILY_ID"

echo ""
echo "🔌 Socket configuration:"
echo "   BearDog: $BEARDOG_SOCKET"
echo "   Songbird: $SONGBIRD_SOCKET"

# Remove stale sockets
rm -f "$BEARDOG_SOCKET" "$SONGBIRD_SOCKET"

# Create logs directory
mkdir -p /tmp/primals
LOG_DIR="/tmp/primals"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 4: START BEARDOG (Genetic Security Provider)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
echo ""
echo "🐕 Starting BearDog..."

"$WORK_DIR/beardog" server \
    --socket "$BEARDOG_SOCKET" \
    --family-id "$FAMILY_ID" \
    > "$LOG_DIR/beardog-${NODE_ID}.log" 2>&1 &
BEARDOG_PID=$!

# Wait for socket
for i in {1..30}; do
    if [[ -S "$BEARDOG_SOCKET" ]]; then
        echo "✅ BearDog started (PID: $BEARDOG_PID)"
        break
    fi
    sleep 0.1
done

if [[ ! -S "$BEARDOG_SOCKET" ]]; then
    echo "❌ BearDog failed to start"
    tail -10 "$LOG_DIR/beardog-${NODE_ID}.log"
    exit 1
fi

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 5: START SONGBIRD (Network Federation)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
echo ""
echo "🐦 Starting Songbird..."

export SONGBIRD_SECURITY_PROVIDER="beardog"
export SONGBIRD_IDENTITY_TAGS="btsp_enabled,beardog:family:${FAMILY_ID}"
export SONGBIRD_UDP_DISCOVERY="true"
export SONGBIRD_UDP_MULTICAST_GROUP="224.0.0.251"
export SONGBIRD_UDP_PORT="2300"

"$WORK_DIR/songbird" server \
    --socket "$SONGBIRD_SOCKET" \
    --beardog-socket "$BEARDOG_SOCKET" \
    > "$LOG_DIR/songbird-${NODE_ID}.log" 2>&1 &
SONGBIRD_PID=$!

# Wait for socket
for i in {1..30}; do
    if [[ -S "$SONGBIRD_SOCKET" ]]; then
        echo "✅ Songbird started (PID: $SONGBIRD_PID)"
        break
    fi
    sleep 0.1
done

if [[ ! -S "$SONGBIRD_SOCKET" ]]; then
    echo "❌ Songbird failed to start"
    tail -10 "$LOG_DIR/songbird-${NODE_ID}.log"
    exit 1
fi

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# STEP 6: DARK FOREST MODE (Encrypted Discovery)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
if [[ "${1:-}" == "--dark" ]]; then
    echo ""
    echo "🌲 Dark Forest Mode: ENABLED"
    echo "   Beacons will be encrypted with family lineage key"
    
    # Derive broadcast key using Blake3 from genesis seed
    BROADCAST_KEY_REQ='{"jsonrpc":"2.0","method":"crypto.blake3_hash","params":{"data":"'"$BEARDOG_GENESIS_SEED"'","context":"dark_forest_broadcast_v1"},"id":1}'
    BROADCAST_KEY_RESP=$(echo "$BROADCAST_KEY_REQ" | nc -N -U "$BEARDOG_SOCKET" 2>/dev/null || true)
    
    if echo "$BROADCAST_KEY_RESP" | grep -q '"hash"'; then
        BROADCAST_KEY=$(echo "$BROADCAST_KEY_RESP" | sed -n 's/.*"hash":"\([^"]*\)".*/\1/p')
        echo "   Broadcast key derived: ${BROADCAST_KEY:0:16}..."
        export DARK_FOREST_BROADCAST_KEY="$BROADCAST_KEY"
        export DARK_FOREST_ENABLED="true"
    else
        echo "   ⚠️ Failed to derive broadcast key, falling back to plain beacons"
    fi
fi

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DEPLOYMENT COMPLETE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ LiveSpore Deployed Successfully!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Running Services:"
echo "  BearDog:  PID $BEARDOG_PID  Socket: $BEARDOG_SOCKET"
echo "  Songbird: PID $SONGBIRD_PID  Socket: $SONGBIRD_SOCKET"
echo ""
echo "Logs:"
echo "  $LOG_DIR/beardog-${NODE_ID}.log"
echo "  $LOG_DIR/songbird-${NODE_ID}.log"
echo ""
echo "To verify genetic lineage with another spore:"
echo "  # On this node:"
echo "  echo '{\"jsonrpc\":\"2.0\",\"method\":\"genetic.generate_lineage_proof\",\"params\":{\"our_family_id\":\"$FAMILY_ID\",\"peer_family_id\":\"<peer_family>\",\"lineage_seed\":\"'\$(base64 -w0 $WORK_DIR/.family.seed)'\"},\"id\":1}' | nc -U $BEARDOG_SOCKET"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Keep running until interrupted
echo "Press Ctrl+C to stop..."
trap "kill $BEARDOG_PID $SONGBIRD_PID 2>/dev/null; exit 0" INT TERM
wait $BEARDOG_PID $SONGBIRD_PID 2>/dev/null || true

