// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2025-2026 ecoPrimals Project

//! NUCLEUS receipt writing for ingest and emit operations.

use anyhow::Result;
use std::path::Path;
use tracing::info;

/// Extract a string from a JSON response, trying multiple JSON pointer
/// paths in priority order. Returns `"pending"` if none match.
pub(super) fn extract_receipt_field<'a>(
    result: &'a serde_json::Value,
    pointers: &[&str],
) -> &'a str {
    for ptr in pointers {
        if let Some(v) = result.pointer(ptr).and_then(|v| v.as_str()) {
            return v;
        }
    }
    "pending"
}

/// Write `receipts/nucleus_ingest.toml` with trio IDs from the signal result.
pub(super) fn write_ingest_receipt(
    pseudospore_dir: &Path,
    result: &serde_json::Value,
    family: &str,
) -> Result<()> {
    let receipts_dir = pseudospore_dir.join("receipts");
    std::fs::create_dir_all(&receipts_dir)?;

    let receipt_path = receipts_dir.join("nucleus_ingest.toml");

    let execution_id = extract_receipt_field(result, &["/execution/execution_id", "/execution_id"]);
    let store_id = extract_receipt_field(
        result,
        &[
            "/receipt/store_id",
            "/execution/nodes/store_content/result/store_id",
        ],
    );
    let dag_id = extract_receipt_field(
        result,
        &[
            "/receipt/dag_session_id",
            "/execution/nodes/dag_session/result/dag_session_id",
        ],
    );
    let ledger_id = extract_receipt_field(
        result,
        &[
            "/receipt/ledger_entry_id",
            "/execution/nodes/ledger_entry/result/ledger_entry_id",
        ],
    );
    let braid_id = extract_receipt_field(
        result,
        &[
            "/receipt/braid_id",
            "/execution/nodes/attribution_braid/result/braid_id",
        ],
    );
    let signature = extract_receipt_field(
        result,
        &[
            "/receipt/signature",
            "/execution/nodes/sign_receipt/result/signature",
        ],
    );

    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let receipt_content = format!(
        r#"# NUCLEUS Ingest Receipt
# Generated by biomeOS nucleus ingest

[receipt]
execution_id = "{execution_id}"
store_id = "{store_id}"
dag_session_id = "{dag_id}"
ledger_entry_id = "{ledger_id}"
braid_id = "{braid_id}"
signature = "{signature}"
family_id = "{family}"
timestamp = {timestamp}
"#,
    );

    std::fs::write(&receipt_path, receipt_content)?;
    info!("  receipt written: {}", receipt_path.display());
    Ok(())
}

/// Write `receipts/nucleus_emit.toml` (symmetric with `nucleus_ingest.toml`).
pub(super) fn write_emit_receipt(
    emit_dir: &Path,
    status: &serde_json::Value,
    family: &str,
) -> Result<()> {
    let receipts_dir = emit_dir.join("receipts");
    std::fs::create_dir_all(&receipts_dir)?;

    let execution_id = extract_receipt_field(status, &["/execution_id", "/execution/execution_id"]);

    let braid_id = extract_receipt_field(
        status,
        &["/receipt/braid_id", "/nodes/resolve_braid/result/braid_id"],
    );

    let signature = extract_receipt_field(
        status,
        &[
            "/receipt/signature",
            "/nodes/sign_emission/result/signature",
        ],
    );

    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let receipt_content = format!(
        r#"# NUCLEUS Emit Receipt
# Generated by biomeOS nucleus emit

[receipt]
execution_id = "{execution_id}"
braid_id = "{braid_id}"
signature = "{signature}"
family_id = "{family}"
timestamp = {timestamp}
"#,
    );

    let receipt_path = receipts_dir.join("nucleus_emit.toml");
    std::fs::write(&receipt_path, receipt_content)?;
    info!("  emit receipt: {}", receipt_path.display());
    Ok(())
}
